### 课程查询列表
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203002"
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "测试课程103",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": ""
}

### 测试异常处理
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "123",
  "pic": "",
  "teachmode": "200002",
  "users": "12357",
  "tags": "",
  "grade": "204001",
  "description": ""
}

### 查询课程详细信息
GET {{content_host}}/content/course/123


### 查询某个课程的课程计划
GET {{content_host}}/content/teachplan/74/tree-nodes

###
GET http://localhost:63040/content/course/1

### 申请验证码
POST {{checkcode_host}}/checkcode/pic

### 校验验证码
POST {{checkcode_host}}/checkcode/verify?key=checkcode:58e45045b83d4983b586d7ddaa332d3e&code=lazj